### ISSUE TITLE
Select a subset of a list to run with a specific campaign.

### ISSUE THREAD

**Issue by japrogramer** [VingtCinq/python-mailchimp#181]
First I would like to create a campaign that only runs on a subset of a list.
So I would like to know how do i assign a subset from a list to a campaign and than run the campaign.

I will periodically need to update the subset every time the users are to be contacted by said campaign. by updating merge fields so that the email is more relevant.

Would my campaign run periodically on its own, or would i need to trigger it. I would prefer to trigger it from an api call.

**Comment by japrogramer** [comment]
Main question here, how do i remove all members from a segment and how do i email users in a segment with a specific email template.

**Comment by stephenross** [comment]
In case you haven't already gotten an answer/solution to this in the last year, you would want to create a segment in your list that you would use as the recipients of your campaign, and based on what you provided, you would want to target the value of a merge field for how that segment is checked. Segments like that are live, so removing the expected value from someone's merge field will remove them from that segment. For example, if you have a merge field called SEND, and you make a segment that looks for 'Yes' in SEND, then clearing the segment would simply involve updating the value of the SEND merge field on all users that you don't want to receive the email to some other value (like 'No'). Segments are checked when the email is sent, so when you create your campaign and schedule it, make sure that your segment has the users you want, and then once you send the campaign, you will be able to see who got the email in the sent_to report for that campaign. From what you are saying about sending the campaign periodically, it sounds like what you want to do is set up a template that contains the bulk of the information you will be sending (the stuff that won't change), and then use that template as a base for a new campaign each time you want to send out a blast, which is the standard practice for getting out things like newsletters and the like.
