### ISSUE TITLE
Occasional  "Member Exists" errors when using 'create_or_update'

### ISSUE THREAD

**Issue by antonkhelou** [VingtCinq/python-mailchimp#182]
I am getting the following error, and other errors in the same type of category (relating to a record of a certain kind already existing).

the error:
```
MailChimpError: {u'status': 400, u'instance': u'<SOME GUID>', u'type': u'http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/', u'detail': u'<SOME EMAIL> is already a list member. Use PUT to insert or update list members.', u'title': u'Member Exists'} 
```
and the code:
```
        interest = <some interest instance>
        user_email_hash = hashlib.md5(user_email.encode('utf')).hexdigest()

        payload = {
            'email_address': user_email,
            'status': 'subscribed',
            'status_if_new': 'subscribed',
            'interests': {interest['id']: True}
        }
        result = self.client.lists.members.create_or_update(
            list_id,
            user_email_hash,
            data=payload
        )
```

Any ideas why I would be getting these occasionally?

**Comment by antonkhelou** [comment]
This was a mistake on my end.

**Comment by pirsquare** [comment]
I've also encountered this problem but it's actually not a bug, but due to the way subscriber's hash is generated.

This error may occur when you try generate subscriber's hash without converting email to lowercase first. You need to convert `John@example.com` to `john@example.com` before generating subscriber hash for Mailchimp.

From Mailchimp's Docs:

> For example, to get the MD5 hash of Urist.McVankab@freddiesjokes.com, convert the address to its lowercase version, which is urist.mcvankab@freddiesjokes.com. The MD5 hash of urist.mcvankab@freddiesjokes.com is 62eeb292278cc15f5817cb78f7790b08.

**Comment by stephenross** [comment]
All endpoints supported by this package that expect a subscriber hash as a required argument will also accept an email address raw as a string. If you need to generate the subscriber hash for other operations, such as updating an email address with the `create_or_update` method on the members endpoint, you can use the internal helper functions `check_subscriber_hash` and `get_subscriber_hash`. If you may get either hashes or email addresses, use the check function. If you will only be passing in email addresses, us the get function that it calls. The get function will verify that the email is a valid format, and then get the hash of the forced lowercase string. The source for all of these can be found at https://github.com/VingtCinq/python-mailchimp/blob/master/mailchimp3/helpers.py.
