### ISSUE TITLE
How to query?

### ISSUE THREAD

**Issue by jrshorton** [VingtCinq/python-mailchimp#204]
Please can you give an example of how to run a query:

`campaigns = client.campaigns.all({'since_send_time' : '2019-05-14T15:30:00+00:00'})`

Was my best guess but it returns all campaigns..

**Comment by joc4ntonio** [comment]
Hello. I hope you found out how to do it.
For me it worked this: r = e.campaigns.all(get_all=False, since_create_time="2019-10-02T00:00:00+00:00").
Remember it expects **queryparams, which is the same as *kwargs; which means Python expects a variable quantity of arguments
